/// Flutter icons PollarIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PollarIcons
///      fonts:
///       - asset: fonts/PollarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PollarIcons {
  PollarIcons._();

  static const _kFontFam = 'PollarIcons';
  static const _kFontPkg = null;

  static const IconData select_saved_account = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData liked = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discover = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accept = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_chat_video = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData see_more = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData character_count = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polls = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData invisible = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multimedia = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gif = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData muted = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mute = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_profile = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visible = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popped_up_menu = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pop_up_menu = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData decline = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_video_player = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like_transition = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause_video_player = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscribed = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_options = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData subscribe = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selected = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_muted = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_selection = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_invisible = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_backward = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skip_forward = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audio = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData url = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_visible = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_remove_circle_1 = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData replay = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_audio = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_remove_circle = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_remove_circle_2 = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_remove = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_check_1 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_remove = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_options_circle_1 = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_up_arrow = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android_back = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_up_arrow = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multiple_pictures = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_options_circle_2 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_check_2 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_muted_notification = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_down_arrow = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData big_down_arrow = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
